### ISSUE TITLE
uri and path generated incorrectly in .job.xml 

### ISSUE THREAD

**Issue by tyrin** [dita-ot/dita-ot#2011]
(I'm seeing a bunch of errors like the one I'm going to describe).
I am getting the following error:

> [gen-list] [DOTX008E][ERROR] File 'file:/Users/tavery/documentation/DITA/source/en/SiteGenesis/SiteGenesisSetup.dita/SiteGenesisSetup.dita/' does not exist or cannot be loaded.

In the ditamap, this topic is referenced as: 
```xml
<topicref href="SiteGenesis/SiteGenesisSetup.dita">
```
It is not referenced by any other topic. It exists at the path described. It is valid DITA. I've made sure the header information for the map and topic is identical to my other files (DOCTYPE etc). 

In the temp files, I'm seeing the following:

**In .job.xml it's doubling the file name:**
```xml
<file
  src="file:/Users/tavery/documentation/DITA/source/en/SiteGenesis/SiteGenesisSetup.dita/SiteGenesisSetup.dita/"
  uri="SiteGenesis/SiteGenesisSetup.dita/SiteGenesisSetup.dita/"
  path="SiteGenesis/SiteGenesisSetup.dita/SiteGenesisSetup.dita" target="true"
  non-conref-target="true"/>
```

**In canditopics.list it's also doubling the name:**
```
SiteGenesis/SiteGenesisSetup.dita/SiteGenesisSetup.dita
```
**In hreftargets.list it's again doubling the name:**
```
SiteGenesis/SiteGenesisSetup.dita/SiteGenesisSetup.dita
```
I'd attach the files, but the editor won't let me.

**Comment by jelovirt** [comment]
Which OS and DITA-OT version? Could you create a Gits with a small test suite?

**Comment by tyrin** [comment]
MacOS version 10.10.4 Yosemite
DITA-OT1.8.4_standard_bin
Not sure what you're asking for the test suite. 
You want me to commit something to a fork?

**Comment by jelovirt** [comment]
You can use [Gist](https://gist.github.com/) to store a set of test suite files and then link that here.

**Comment by tyrin** [comment]
My boss forbade posting any files due to objections from our legal department.
Looks like one malformed internal link caused whatever does the uri generation to use topicID.dita#topicID.dita/elementID for all internal links in the topic and also created errors for external links in which the folder of the current topic was inserted before the file path to the external topic. I'm guessing this is just a weird edge case and you guys can ignore it. 
I was able to fix it by making sure all the xrefs were corrected formatted and adding the filename to the internal links (even though that shouldn't be necessary).

**Comment by jelovirt** [comment]
We actually prefer dummy content, because that can be stripped down to bare minimum, like a single `<xref>` in a topic.

**Comment by simonbate** [comment]
I can reproduce this with the files I've uploaded in BadDir2.zip.

I'm on 2.3.1. I've eliminated all distractions that I thought were causing the problem, yet the problem still remains. The type and format attributes do not have an effect on the problem. 

I'm getting DOTX008E in gen-list.

[BadDir2.zip](https://github.com/dita-ot/dita-ot/files/554214/BadDir2.zip)

**Comment by jelovirt** [comment]
@simonbate The `shorty/test_name.dita` file has custom DTD that's not bundled in the ZIP.

**Comment by simonbate** [comment]
As Homer Simpson says: Doh!
I was migrating things to a new (2.x) OT, but Oxygen was still using the catalog from the old (1.8) OT, with plugins for the custom DTD. That's why it all validated, but wouldn't parse in the 2.x OT.

I am left with the feeling, though, that it would be good if gen-list could provide a bit more info about why the file "couldn't be loaded". But I think that's a separate ticket.

Thanks for the pointer.

**Comment by jelovirt** [comment]
@simonbate I mean if you can update the ZIP to contain only files that use the built-in DTDs, so we can verify this issue still exists.

**Comment by simonbate** [comment]
I believe the issue no longer exists. Here's an updated BadDir2.zip. 
[BadDir2.zip](https://github.com/dita-ot/dita-ot/files/556525/BadDir2.zip)

**Comment by jelovirt** [comment]
Ok, will close this then.
