### ISSUE TITLE
Input line too long in a windows system

### ISSUE THREAD

**Issue by lionelmoi** [dita-ot/dita-ot#2827]
## Expected Behavior
DITA-OT outputs.

## Actual Behavior
DITA-OT crashes right away with this error message:

```
C:\workspace\gradle\dita-transform\build\PI\build\ditaotPI>bin\dita.bat --input=C:\workspace\RDDOC_technical_documentation\DITA\E1007_PI_publi.ditamap --format=pi
La ligne entrée est trop longue.
"C:\workspace\gradle\dita-transform\build\PI\build\ditaotPI\bin\..\config\env.bat" était inattendu.

```
Which translates to 
```
Input line is too long.
"C:\workspace\gradle\dita-transform\build\PI\build\ditaotPI\bin\..\config\env.bat" was unexpected.
```

## Possible Solution
Use the script closer to C: but it sounds like a regression.
Remove the need for env.at by adding the file in the classpath using gradle.

## Steps to Reproduce
Launch DITA-OT deep into the filesystem of a windows machine.

## Environment

* DITA-OT version: 3.0
* Operating system and version:
  Windows
* How did you run DITA-OT?
  `dita` command
* Transformation type:
  PDF

**Comment by lief-erickson** [comment]
+1

I'm experiencing this too.

**Comment by raducoravu** [comment]
👍 We also experience this problem with DITA OT 3.0 although on the same Windows OS with the same command line arguments DITA OT 2.x does not have this problem.

**Comment by raducoravu** [comment]
Problem is that "env.bat" has become huge because it lists all JAR libraries from all plugins, the DITA OT plugin with the most number of JAR libraries referenced being this one:

/oxygen-dita-ot-3.x/plugins/org.lwdita/plugin.xml

Ideally the ""dita.conductor.lib.import"" would allow plugins specifying the library paths as wildcards. Then these wildcards would go to the "env.bat" and then used on the "-cp" command line and Java 6 or newer supports wildcards.

Or:
Remove the "env.bat" and "env.sh" completely and on the method:

org.dita.dost.invoker.Main.runBuild(ClassLoader)

create your own URLClassLoader over the base one and in your URLClassLoader load the JAR libraries contributed by each plugin. You can look in the merged "plugins.xml" to find this out.

**Comment by raducoravu** [comment]
Using our own class loader in the org.dita.dost.invoker.Main could also be useful if we want to isolate the JAR libraries contributed by a certain transtype. If a certain transtype is invoked, only its jar libraries and the common jar libraries could be loaded + the libraries from extra plugins this particular transtype depends on.

**Comment by jelovirt** [comment]
I would prefer to stay away from using a custom class loader as long a possible. Preferably the LwDITA plugin should be fixed to only import JARs that are actually needed.

**Comment by raducoravu** [comment]
One other possibility would be if when the "org.lwdita-2.0.2.jar" is created its MANIFEST.MF has classpath entries listing all other JARS from flexmark:

https://docs.oracle.com/javase/tutorial/deployment/jar/downman.html

So the plugin.xml for the "lwdita" would just need to point to the main "org.lwdita-2.0.2.jar".

**Comment by raducoravu** [comment]
I'm constantly hitting this problem when trying to publish from the command line on Windows.

**Comment by jelovirt** [comment]
[#2976](https://github.com/dita-ot/dita-ot/pull/2976/files#diff-c3940e52875d192cce1651fe17fc087c) changes the classpath for FOP quite a lot because we bundle a fat JAR for Batik. Have you tried whether this change fixes this issue for most cases?

**Comment by raducoravu** [comment]
It helps but the problem is still there depending on the folder path in which the DITA OT is located.
For example for some of the automated tests I run on Windows, the DITA OT is installed in a folder path like this:

                D:\projects\oxygen-dita-publishing-integration-tests\oxygen-webhelp-responsive-tests\oxygen-dita-ot-3.0

so in order to run tests or run the integrator I have to manually edit the "env.bat", remove all references to the FOP, Batik and lwdita JARs and reduce it to:

			set "CLASSPATH=%CLASSPATH%;%DITA_HOME%\plugins\com.oxygenxml.common\lib\jaxb-api-2.3.0.jar"
			set "CLASSPATH=%CLASSPATH%;%DITA_HOME%\plugins\com.oxygenxml.common\lib\jaxb-core-2.3.0.jar"
			set "CLASSPATH=%CLASSPATH%;%DITA_HOME%\plugins\com.oxygenxml.common\lib\jaxb-impl-2.3.0.jar"
			set "CLASSPATH=%CLASSPATH%;%DITA_HOME%\plugins\com.oxygenxml.common\lib\activation-1.1.1.jar"
			set "CLASSPATH=%CLASSPATH%;%DITA_HOME%\plugins\com.oxygenxml.common\lib\ant-contrib-1.0b3.jar"
			set "CLASSPATH=%CLASSPATH%;%DITA_HOME%\plugins\com.oxygenxml.dost.patches\lib\oxygen-dost-patches.jar"
			set "CLASSPATH=%CLASSPATH%;%DITA_HOME%\plugins\com.oxygenxml.highlight\lib\xslthl-2.1.1.jar"

**Comment by xephon2** [comment]
I'm now getting this too on Windows 10 with DITA-OT 2.5.4.

**Comment by raducoravu** [comment]
Yes, it also helps to install DITA OT very close to the root drive letter, for example "D:\DITA-OT2.5.4" instead of having a very long folder path in which you copied and are running the DITA OT.

**Comment by xephon2** [comment]
@infotexture, maybe you could add a note in the docs and explain how to set the `MAX_PATH` parameter, see https://mspoweruser.com/ntfs-260-character-windows-10/.

**Comment by jelovirt** [comment]
@xephon2, AFAICT the problem is not the length of a file path. The problem is the length of the argument to a command, in this case the classpath.

**Comment by dan-caprioara** [comment]
Hello @jelovirt,

As said before, the main problem we face in oXygen is that our com.oxygenxml plugins refer a collection of jar files whose paths are concatenated with the ones from org.lwdita result in a classpath 
longer than the limit of the shell. We need to move on to DITA-OT 3.x and this is a major problem for the users that will execute dita.bat from the command line.

We found a solution for that by using wildcards. I attached a patch. Shortly these are the changes:
1. The org.dita.dost.platform.Integrator  accepts now the "*" wildcard for the lib filenames. This means the DITA-OT plugins can use now this notation to refer jars from their lib directories.
2. Because the Ant Launcher does not expand wildcards, a new implementation of the AntMain is added to the dost.jar that delegates to the current implementation of "org.dita.dost.invoker.Main". It creates a classloader with the expanded wildcard classpath entries. This classloader is created only when wildcards are detected.
3. The dita.bat/dita.sh file now uses this new AntMain.

I think these changes should go into dost, so the wildcard support is availabe in one of the next DITA-OT releases.
[widlcards-oxygen-patch.txt](https://github.com/dita-ot/dita-ot/files/2667571/widlcards-oxygen-patch.txt)

**Comment by dan-caprioara** [comment]
By the way, we plan to use the wildcard in the lwdita plugin of the oXygen distribution. Using wildcards in the com.oxygenxml plugins is not enough. The best would be to simply check and remove the jars that are not needed and keep the direct references, so the backward compatibility  is preserved.

**Comment by thendarion** [comment]
windows is the worst, amirite? :D 

srsly tho, we should totally do something about env.bat eventually

what if a jar file was created instead that like imported all the other jars and we only added the collector jar to the classpath? would that work?

**Comment by thendarion** [comment]
so if java classpath supports wildcards, then why can't I write lib/* in feature extension="dita.conductor.lib.import" in plugin.xml? it would make my jars easier to maintain 😅 

ref: https://docs.oracle.com/javase/8/docs/technotes/tools/windows/classpath.html#A1100762

the import part has to recognise an asterisk and maybe validate the folder instead of the file then, but I believe that should be the only obstacle standing in our way

**Comment by thendarion** [comment]
or dita.bat could be replaced by dita.ps1 :D
PowerShell has better features than CMD

**Comment by chrizzbee** [comment]
an old thread, i know. since upgrading to ot 4.2.1 i now also get this error. what are the recommended steps now to get around it? thanks.

**Comment by raducoravu** [comment]
@chrizzbee Oxygen XML Editor's bundled DITA OT has patches to avoid this problem. With a plain DITA OT installation if you do not use Markdown content in your DITA Map I would probably remove the entire "org.lwdita" plugin as it has lots of library references, then run again the "dita --install", also I would place the DITA OT in a shorter folder path, maybe on "D:\DITA-OT".

**Comment by chrizzbee** [comment]
yes, removing lwdita (+some others i did not use) solved the problem. thanks!

**Comment by AndeeZee** [comment]
Any updates on this one? In 2026: still the same issue. Since I need lwdita, removing the mentioned plugins won't help.
