### ISSUE TITLE
NPE from preprocess for links to copy-to result

### ISSUE THREAD

**Issue by robander** [dita-ot/dita-ot#2841]
## Expected Behavior

Warning: the whole context here is iffy, but whatever the result, we shouldn't be crashing the build with a null pointer error. I'd rather be using keys/keyref but have `href` for historical reasons, and because this same functionality doesn't work today with keys.

I have a topic in my map that I want to appear twice. So, I use `@copy-to`:
```
<topicref href="alsocopy.dita"/>
<topicref href="alsocopy.dita" copy-to="alsocopy-newname.dita"/>
```

I also want to link to the copies individually. So, I've got this:
```
<ul>
<li>Original copy of a copied file, with href: <xref href="alsocopy.dita"/></li>
<li>Copied version of something also generated, with href: <xref href="alsocopy-newname.dita"/></li>
</ul>
```

(Again, yes, keys are the correct solution. But they don't work today. Another issue will be coming for that.)

Today, these links work with PDF and `preprocess2`, though I have to ignore an error from `topic-reader` about a missing "file". With HTML5 and `preprocess`, the build crashes with `java.lang.NullPointerException` during the `copy-to` target.

## Possible Solution

Not sure yet of best solution. I don't want to _remove_ the working link from PDF, so it would be great if the link worked in HTML5 / preprocess. But, `preprocess2` is the preferred way to go, so the result here may simply be to clean up the `copy-to` code enough that it avoids the NPE crash.

Sample files attached. Building the map to `html5` will generate the NPE failure with DITA-OT 2.5 and 3.0 (and probably older releases but haven't tested).

[npe.zip](https://github.com/dita-ot/dita-ot/files/1458626/npe.zip)

**Comment by robander** [comment]
Ah looks like this is already open against 2.4 (and 2.5) as #2733.

**Comment by robander** [comment]
Debugging against 3.0 using the sample zip attached above, the NPE comes from this line: https://github.com/dita-ot/dita-ot/blob/hotfix/3.0.1/src/main/java/org/dita/dost/module/CopyToModule.java#L162

Error only comes up when the copy-to result file is linked-to; in that case, the `.job.xml` file is missing an entry for the copied version. In my test -- when I link to the copy, `.job.xml` has this:
```
<file 
   src="file:/C:/DCS/3.0/test/copyto/bug1/alsocopy.dita" 
   uri="alsocopy.dita" 
   path="alsocopy.dita" 
   result="file:/C:/DCS/3.0/test/copyto/bug1/alsocopy.dita" format="dita" target="true"></file>
```

When I remove the `<xref>` that targets the copy, `.job.xml` has two entries:
```
<file 
   src="file:/C:/DCS/3.0/test/copyto/bug1/alsocopy.dita" 
   uri="alsocopy-newname.dita" 
   path="alsocopy-newname.dita" 
   result="file:/C:/DCS/3.0/test/copyto/bug1/alsocopy-newname.dita" 
   format="dita" target="true"></file>
<file 
   src="file:/C:/DCS/3.0/test/copyto/bug1/alsocopy.dita" 
   uri="alsocopy.dita" 
   path="alsocopy.dita" 
   result="file:/C:/DCS/3.0/test/copyto/bug1/alsocopy.dita" 
   format="dita" target="true"></file>
```

**Comment by robander** [comment]
Fixed with #2936

**Comment by mironovalexey** [comment]
Excuse me, but this is still relevant for both 3.0.4 and 3.1.

We have 
`[gen-list] [DOTX008E][ERROR] File '../npe/alsocopy-newname.dita'` does not exist or cannot be loaded.
in log.

For HTML5 output we have no corresponding link in job.xml and `<xref href="alsocopy-newname.dita"/>` is not resolved.
```
[topicpull] I/O error reported by XML parser processing .../tmp/alsocopy-newname.dita: .../tmp/alsocopy-newname.dita ...
[topicpull] .../npe/links.dita:8:96: [DOTX031E][ERROR]: The file alsocopy-newname.dita is not available to resolve link information.
```

For PDF situation is better:  [DOTX008E][ERROR], but .job.xml is ok and link is resolved.

**Comment by robander** [comment]
The fix was made using support for keys, to avoid the race condition of "do I evaluate the `@href` first and report an error, or do I allow references to files that might exist later". The DITA specification is unclear about this situation (it is not addressed) but it implies that the specified `@href` value should be a valid local reference to a file that exists. So there are a couple of aspects to the fix:

- We should never be giving the null pointer error for valid markup -- this markup is valid in the source, even if it's not clear how it should resolve, so code problem that led to the the NPE was corrected.
- It's now possible to achieve the intended result, but with keys. On the definition that specifies the new name, you can specify a key:
`<topicref href="original-name.dita" copy-to="alsocopy-newname.dita" keys="test"/>`
and then change the xref from `<xref href="alsocopy-newname.dita"/>` to `<xref keyref="test"/>`.

Using keys, the result is unambiguous and does not result in questions about processing order. The key refers to the definition, which provides the name of the result topic for linking.

Hope that helps - given that keys can get the desired function without any of the processing complexity, I'm not expecting the markup with `@href` to be supported for links to copies.

**Comment by mironovalexey** [comment]
Robert, thank you for the detailed answer. I understand that we need to use keys (this also was discussed [here]( https://github.com/dita-ot/dita-ot/issues/2989#issuecomment-394209815)).

But look, here we have a litlle lack of consistency.
1. PDF anf HTML output give different results. Since link to a copy resolves for PDF, one might expect it works for other outputs too.
2. _specified @href value should be a valid local reference to a file that exists_. But `<xref keyref="test"/>` is a link to a nonexistent file.
