### ISSUE TITLE
Extra problems reported when using in memory storage

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3621]
I got this null pointer exception when publishing the Oxygen user's manual to HTML5 using in memory storage

     C:\Users\radu_coravu\Downloads\dita-ot-develop(2)\dita-ot-develop\src\main\plugins\org.dita.base\build.xml:29: The following error occurred while executing this line:
      C:\Users\radu_coravu\Downloads\dita-ot-develop(2)\dita-ot-develop\src\main\plugins\org.dita.base\build_preprocess.xml:266: java.lang.NullPointerException
	at org.dita.dost.ant.types.JobSourceSet.getResults(JobSourceSet.java:65)
	at org.dita.dost.ant.types.JobSourceSet.iterator(JobSourceSet.java:102)
	at org.apache.tools.ant.types.resources.Resources$MyCollection$MyIterator.hasNext(Resources.java:108)
	at java.util.Iterator.forEachRemaining(Unknown Source)

**Comment by jelovirt** [comment]
Probably https://github.com/dita-ot/dita-ot/blob/develop/src/main/java/org/dita/dost/ant/types/JobSourceSet.java#L65

```java
} else if (f.src.getScheme().equals("file")) {
```

where `getScheme()` is null. @raducoravu could you add debug logging that will log `f.src` so I can see what the URL looks like. Whether it's a source file or some external reference.

**Comment by raducoravu** [comment]
@jelovirt I added logging, the entire "f.src" is null.

**Comment by raducoravu** [comment]
So I logged this:

                   System.err.println("ORIG " + f.file);
                System.err.println("TEMP " + tempFile);
                System.err.println("Scheme " + f.src);

and I obtained:

      [pathconvert] ORIG topics\content_fusion_task_details-x2.dita
     [pathconvert] TEMP D:\git-projects\userguide-private\DITA\temp\html5\topics\content_fusion_task_details-x2.dita
     [pathconvert] Scheme null

There is a copy-to somewhere in the DITA Map:

         <topicref href="../topics/content_fusion_task_details.dita"
        copy-to="../topics/content_fusion_task_details-x2.dita"/>

**Comment by raducoravu** [comment]
Other than that, if I skip in the code over "f.src" which are null there is a speed improvement from 236 to 97 seconds.
But: in the [conref] stage none of the content references seem to be resolved. We are using conkeyrefs, no key scope and no branch filtering.
So I get lots of errors like:

    [DOTX010E]: Unable to find target for conref="../reusables/topics/reusables-editing-documents.dita#remove-text-dlentry".

**Comment by raducoravu** [comment]
And I also get a lot of warning about the chunks we have:


    [DOTX061W]: ID 'dcpp_how_to_style_the_indexterms' was used in topicref tag but did not reference a topic element. The href attribute on a topicref element should only reference topic level elements.
     [DOTX023W]: Unable to retrieve navtitle from target: 'Chunk216651295.dita#dcpp_how_to_style_the_indexterms'.

and all copy-to topics are not present.

**Comment by jelovirt** [comment]
Is your user manual the public one in GitHub? Which commit are you trying to build?

**Comment by raducoravu** [comment]
You can use the master branch here:
https://github.com/oxygenxml/userguide

**Comment by jelovirt** [comment]
Can't reproduce. I wonder if this is some Windows related bug.

**Comment by jelovirt** [comment]
The conref error messages were a bug, fixed by #3624

**Comment by raducoravu** [comment]
I confirm the conref problem seems to be fixed.
I get the NullPointerException also on Mac when running:

      sh dita -i ../../../../userguide-master/DITA/UserManual.ditamap -f html5 -filter ../../../../userguide-master/DITA/ditaval/editor-sa.ditaval --store-type=memory -d -v

So what I do on Mac is:
 1. Download the entire source code as a zip: https://github.com/dita-ot/dita-ot 
 1. Run "gradlew" in the dita-ot folder
 1. Download the Oxygen userguide DITA content as a zip from: https://github.com/oxygenxml/userguide
 1. Run the command line specified above.

The NPE stack trace is not visible in the command line, I can see the stack trace if I run the publishing from Oxygen which delegates directly to the ANT code.

**Comment by raducoravu** [comment]
One other thing I noticed, without any memory or parallel processing improvement, publishing the Oxygen user guide with Java 15 is slowed than publishing with Java 1.8 (6 minutes as opposed to 4 minutes).

**Comment by jelovirt** [comment]
Ok, was able to reproduce because I didn't know you needed to use a filter.

**Comment by raducoravu** [comment]
@jelovirt I confirm the null pointer exception can no longer be reproduced with your code , thanks.
I still get lots of warnings like this with the storage-type set to "memory":

    [move-meta] Processing file:/Users/raducoravu/Downloads/userguide-master/DITA/temp/html5/UserManual.ditamap
    [move-meta] Warning at char 9 in xsl:sequence/@select on line 60 column 69 of mappullImpl.xsl:
    [move-meta]   FODC0002: I/O error reported by XML parser processing
    [move-meta]   file:/Users/raducoravu/Downloads/userguide-master/DITA/temp/html5/Chunk395390874.dita:
    [move-meta]   /Users/raducoravu/Downloads/userguide-master/DITA/temp/html5/Chunk395390874.dita (No such
    [move-meta]   file or directory)
    [move-meta] file:/Users/raducoravu/Downloads/userguide-master/DITA/maps/chapter-configure-application.ditamap:48:70: [DOTX061W][WARN]: ID 'set-parameter-in-startup-script' was used in topicref tag but did not reference a topic element. The href attribute on a topicref element should only reference topic level elements. 
     [move-meta] file:/Users/raducoravu/Downloads/userguide-master/DITA/maps/chapter-configure-application.ditamap:48:70: [DOTX023W][WARN]: Unable to retrieve navtitle from target: 'Chunk395390874.dita#set-parameter-in-startup-script'. 

and there are no such errors when publishing with "file" storage.
Should I open a new issue about these problems? Or make the subject of this issue more generic?

**Comment by raducoravu** [comment]
I confirm the latest fix removes the warnings reported in the move-meta stage.
Unfortunately publishing to HTML using that command line and steps specified above I still get 41 extra errors that I do not get with storage-type=file.
I'm attaching a zip with an HTML table containing all the extra problems. None of the problems appears using storage-type=file:
[problems.html.zip](https://github.com/dita-ot/dita-ot/files/5492294/problems.html.zip)

**Comment by jelovirt** [comment]
The remaining issues should be reported in new issue.
